apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
    version: v2
spec:
  replicas: 2
  selector:
      matchLabels:
          service: reverseproxy
  template:
      metadata:
        labels: 
          service: reverseproxy
          version: v2
      spec:
          containers:
          - name: reverseproxy
            image: welldone90/reverseproxy
            imagePullPolicy: Always
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "1024Mi"
                cpu: "5000m"
            ports:
            - containerPort: 8080
          restartPolicy: Always

